import {
  PAGE_RUNTIME_ADAPTER_SCRIPT_FILES,
  PAGE_RUNTIME_PRELUDE_SCRIPT_FILES,
  PAGE_RUNTIME_TAIL_SCRIPT_FILES,
  PAGE_RUNTIME_WEBMCP_SCRIPT_FILES,
} from "./layers.js";

export const PAGE_RUNTIME_SCRIPT_FILES = Object.freeze([
  ...PAGE_RUNTIME_WEBMCP_SCRIPT_FILES,
  ...PAGE_RUNTIME_PRELUDE_SCRIPT_FILES,
  ...Object.values(PAGE_RUNTIME_ADAPTER_SCRIPT_FILES),
  ...PAGE_RUNTIME_TAIL_SCRIPT_FILES,
]);
